export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';
export const USER_EDIT_FAILED = 'USER_EDIT_FAILED';
